[package]
name = "algo_trader_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
simplelog = "0.12"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
rand = "0.8"
